# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\AccountPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountPage(object):
    def setupUi(self, AccountPage):
        AccountPage.setObjectName("AccountPage")
        AccountPage.resize(1920, 1080)
        AccountPage.setMinimumSize(QtCore.QSize(1920, 1080))
        AccountPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(AccountPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, -20, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\AccountPage.png"))
        self.label.setObjectName("label")
        self.AccountBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccountBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.AccountBackBtn.setFont(font)
        self.AccountBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.AccountBackBtn.setObjectName("AccountBackBtn")
        self.AccountUsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.AccountUsernameLabel.setGeometry(QtCore.QRect(300, 180, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.AccountUsernameLabel.setFont(font)
        self.AccountUsernameLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.AccountUsernameLabel.setObjectName("AccountUsernameLabel")
        self.AccountPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.AccountPasswordLabel.setGeometry(QtCore.QRect(300, 320, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.AccountPasswordLabel.setFont(font)
        self.AccountPasswordLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.AccountPasswordLabel.setObjectName("AccountPasswordLabel")
        self.ChangeUsernameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ChangeUsernameBtn.setGeometry(QtCore.QRect(680, 180, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ChangeUsernameBtn.setFont(font)
        self.ChangeUsernameBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ChangeUsernameBtn.setObjectName("ChangeUsernameBtn")
        self.ChangePasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ChangePasswordBtn.setGeometry(QtCore.QRect(760, 320, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ChangePasswordBtn.setFont(font)
        self.ChangePasswordBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ChangePasswordBtn.setObjectName("ChangePasswordBtn")
        self.NewUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.NewUsername.setEnabled(False)
        self.NewUsername.setGeometry(QtCore.QRect(910, 180, 371, 51))
        self.NewUsername.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    ")
        self.NewUsername.setObjectName("NewUsername")
        self.NewPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.NewPassword.setEnabled(False)
        self.NewPassword.setGeometry(QtCore.QRect(910, 320, 371, 51))
        self.NewPassword.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.NewPassword.setObjectName("NewPassword")
        self.AccountBalanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.AccountBalanceLabel.setGeometry(QtCore.QRect(300, 460, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.AccountBalanceLabel.setFont(font)
        self.AccountBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.AccountBalanceLabel.setObjectName("AccountBalanceLabel")
        self.ChangeBalanceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ChangeBalanceBtn.setGeometry(QtCore.QRect(680, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ChangeBalanceBtn.setFont(font)
        self.ChangeBalanceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ChangeBalanceBtn.setObjectName("ChangeBalanceBtn")
        self.DeleteLabel = QtWidgets.QLabel(self.centralwidget)
        self.DeleteLabel.setGeometry(QtCore.QRect(90, 770, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteLabel.setFont(font)
        self.DeleteLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DeleteLabel.setObjectName("DeleteLabel")
        self.YesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.YesBtn.setGeometry(QtCore.QRect(740, 770, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.YesBtn.setFont(font)
        self.YesBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.YesBtn.setObjectName("YesBtn")
        self.WarrningLabel = QtWidgets.QLabel(self.centralwidget)
        self.WarrningLabel.setGeometry(QtCore.QRect(90, 820, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WarrningLabel.setFont(font)
        self.WarrningLabel.setStyleSheet("QLabel {\n"
"    color: Red;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.WarrningLabel.setObjectName("WarrningLabel")
        self.EYERadio = QtWidgets.QRadioButton(self.centralwidget)
        self.EYERadio.setGeometry(QtCore.QRect(680, 320, 71, 51))
        self.EYERadio.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.EYERadio.setObjectName("EYERadio")
        self.KeepNewUsernameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.KeepNewUsernameBtn.setEnabled(False)
        self.KeepNewUsernameBtn.setGeometry(QtCore.QRect(1300, 180, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.KeepNewUsernameBtn.setFont(font)
        self.KeepNewUsernameBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.KeepNewUsernameBtn.setObjectName("KeepNewUsernameBtn")
        self.KeepNewPasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.KeepNewPasswordBtn.setEnabled(False)
        self.KeepNewPasswordBtn.setGeometry(QtCore.QRect(1300, 320, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.KeepNewPasswordBtn.setFont(font)
        self.KeepNewPasswordBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.KeepNewPasswordBtn.setObjectName("KeepNewPasswordBtn")
        self.NewBalance = QtWidgets.QLineEdit(self.centralwidget)
        self.NewBalance.setEnabled(False)
        self.NewBalance.setGeometry(QtCore.QRect(910, 460, 371, 51))
        self.NewBalance.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.NewBalance.setObjectName("NewBalance")
        self.KeepNewBalanceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.KeepNewBalanceBtn.setEnabled(False)
        self.KeepNewBalanceBtn.setGeometry(QtCore.QRect(1300, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.KeepNewBalanceBtn.setFont(font)
        self.KeepNewBalanceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.KeepNewBalanceBtn.setObjectName("KeepNewBalanceBtn")
        AccountPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AccountPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        AccountPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AccountPage)
        self.statusbar.setObjectName("statusbar")
        AccountPage.setStatusBar(self.statusbar)

        self.retranslateUi(AccountPage)
        QtCore.QMetaObject.connectSlotsByName(AccountPage)

    def retranslateUi(self, AccountPage):
        _translate = QtCore.QCoreApplication.translate
        AccountPage.setWindowTitle(_translate("AccountPage", "MainWindow"))
        self.AccountBackBtn.setText(_translate("AccountPage", "<"))
        self.AccountUsernameLabel.setText(_translate("AccountPage", "Username"))
        self.AccountPasswordLabel.setText(_translate("AccountPage", "********"))
        self.ChangeUsernameBtn.setText(_translate("AccountPage", "✏"))
        self.ChangePasswordBtn.setText(_translate("AccountPage", "✏"))
        self.AccountBalanceLabel.setText(_translate("AccountPage", "background-color: transparent;"))
        self.ChangeBalanceBtn.setText(_translate("AccountPage", "✏"))
        self.DeleteLabel.setText(_translate("AccountPage", "Do you want to delete the acccount?"))
        self.YesBtn.setText(_translate("AccountPage", "✓"))
        self.WarrningLabel.setText(_translate("AccountPage", "your information will be lost forever"))
        self.EYERadio.setText(_translate("AccountPage", "👁"))
        self.KeepNewUsernameBtn.setText(_translate("AccountPage", "✓"))
        self.KeepNewPasswordBtn.setText(_translate("AccountPage", "✓"))
        self.KeepNewBalanceBtn.setText(_translate("AccountPage", "✓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AccountPage = QtWidgets.QMainWindow()
    ui = Ui_AccountPage()
    ui.setupUi(AccountPage)
    AccountPage.show()
    sys.exit(app.exec_())
