# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\BeyoncePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeyoncePage(object):
    def setupUi(self, BeyoncePage):
        BeyoncePage.setObjectName("BeyoncePage")
        BeyoncePage.resize(1920, 1080)
        BeyoncePage.setMinimumSize(QtCore.QSize(1920, 1080))
        BeyoncePage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(BeyoncePage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\BeyoncePage.png"))
        self.label.setObjectName("label")
        self.BeyonceBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BeyonceBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.BeyonceBackBtn.setFont(font)
        self.BeyonceBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BeyonceBackBtn.setObjectName("BeyonceBackBtn")
        self.DateBeyonceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateBeyonceComboBox.setGeometry(QtCore.QRect(330, 560, 261, 41))
        self.DateBeyonceComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateBeyonceComboBox.setObjectName("DateBeyonceComboBox")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.BeyoncePriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeyoncePriceLabel.setGeometry(QtCore.QRect(70, 490, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BeyoncePriceLabel.setFont(font)
        self.BeyoncePriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BeyoncePriceLabel.setObjectName("BeyoncePriceLabel")
        self.DateBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateBeyonceLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateBeyonceLabel.setFont(font)
        self.DateBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateBeyonceLabel.setObjectName("DateBeyonceLabel")
        self.QuantityBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityBeyonceLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityBeyonceLabel.setFont(font)
        self.QuantityBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityBeyonceLabel.setObjectName("QuantityBeyonceLabel")
        self.QuantityCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QuantityCheckBtn.setGeometry(QtCore.QRect(600, 810, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityCheckBtn.setFont(font)
        self.QuantityCheckBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.QuantityCheckBtn.setObjectName("QuantityCheckBtn")
        self.RowBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowBeyonceLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowBeyonceLabel.setFont(font)
        self.RowBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowBeyonceLabel.setObjectName("RowBeyonceLabel")
        self.SeatBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatBeyonceLabel.setGeometry(QtCore.QRect(70, 740, 521, 121))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatBeyonceLabel.setFont(font)
        self.SeatBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatBeyonceLabel.setObjectName("SeatBeyonceLabel")
        self.RowBeyonceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowBeyonceComboBox.setGeometry(QtCore.QRect(330, 680, 261, 41))
        self.RowBeyonceComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowBeyonceComboBox.setObjectName("RowBeyonceComboBox")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.TotalBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalBeyonceLabel.setGeometry(QtCore.QRect(140, 870, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBeyonceLabel.setFont(font)
        self.TotalBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBeyonceLabel.setObjectName("TotalBeyonceLabel")
        self.TotalBeyonceLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalBeyonceLabelValue.setGeometry(QtCore.QRect(330, 870, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBeyonceLabelValue.setFont(font)
        self.TotalBeyonceLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBeyonceLabelValue.setObjectName("TotalBeyonceLabelValue")
        self.PayBeyonceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayBeyonceBtn.setEnabled(False)
        self.PayBeyonceBtn.setGeometry(QtCore.QRect(1460, 940, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayBeyonceBtn.setFont(font)
        self.PayBeyonceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayBeyonceBtn.setObjectName("PayBeyonceBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 261, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.BeyonceBalanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeyonceBalanceLabel.setGeometry(QtCore.QRect(330, 490, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BeyonceBalanceLabel.setFont(font)
        self.BeyonceBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BeyonceBalanceLabel.setObjectName("BeyonceBalanceLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 740, 276, 130))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SeatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SeatLayout.setContentsMargins(0, 0, 0, 0)
        self.SeatLayout.setObjectName("SeatLayout")
        self.checkBox26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox26.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox26.setObjectName("checkBox26")
        self.SeatLayout.addWidget(self.checkBox26, 0, 5, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox29.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox29.setObjectName("checkBox29")
        self.SeatLayout.addWidget(self.checkBox29, 3, 5, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox19.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox19.setObjectName("checkBox19")
        self.SeatLayout.addWidget(self.checkBox19, 3, 3, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox9.setObjectName("checkBox9")
        self.SeatLayout.addWidget(self.checkBox9, 3, 1, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox24.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox24.setObjectName("checkBox24")
        self.SeatLayout.addWidget(self.checkBox24, 3, 4, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox6.setObjectName("checkBox6")
        self.SeatLayout.addWidget(self.checkBox6, 0, 1, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox22.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox22.setObjectName("checkBox22")
        self.SeatLayout.addWidget(self.checkBox22, 1, 4, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox28.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox28.setObjectName("checkBox28")
        self.SeatLayout.addWidget(self.checkBox28, 2, 5, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox17.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox17.setObjectName("checkBox17")
        self.SeatLayout.addWidget(self.checkBox17, 1, 3, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox21.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox21.setObjectName("checkBox21")
        self.SeatLayout.addWidget(self.checkBox21, 0, 4, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox13.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox13.setObjectName("checkBox13")
        self.SeatLayout.addWidget(self.checkBox13, 2, 2, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox30.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox30.setObjectName("checkBox30")
        self.SeatLayout.addWidget(self.checkBox30, 4, 5, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox11.setObjectName("checkBox11")
        self.SeatLayout.addWidget(self.checkBox11, 0, 2, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox15.setObjectName("checkBox15")
        self.SeatLayout.addWidget(self.checkBox15, 4, 2, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox16.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox16.setObjectName("checkBox16")
        self.SeatLayout.addWidget(self.checkBox16, 0, 3, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox23.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox23.setObjectName("checkBox23")
        self.SeatLayout.addWidget(self.checkBox23, 2, 4, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox1.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox1.setObjectName("checkBox1")
        self.SeatLayout.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox3.setObjectName("checkBox3")
        self.SeatLayout.addWidget(self.checkBox3, 2, 0, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox20.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox20.setObjectName("checkBox20")
        self.SeatLayout.addWidget(self.checkBox20, 4, 3, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox18.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox18.setObjectName("checkBox18")
        self.SeatLayout.addWidget(self.checkBox18, 2, 3, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox2.setObjectName("checkBox2")
        self.SeatLayout.addWidget(self.checkBox2, 1, 0, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox27.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox27.setObjectName("checkBox27")
        self.SeatLayout.addWidget(self.checkBox27, 1, 5, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox4.setObjectName("checkBox4")
        self.SeatLayout.addWidget(self.checkBox4, 3, 0, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox10.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox10.setObjectName("checkBox10")
        self.SeatLayout.addWidget(self.checkBox10, 4, 1, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox14.setObjectName("checkBox14")
        self.SeatLayout.addWidget(self.checkBox14, 3, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox12.setObjectName("checkBox12")
        self.SeatLayout.addWidget(self.checkBox12, 1, 2, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox5.setObjectName("checkBox5")
        self.SeatLayout.addWidget(self.checkBox5, 4, 0, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox7.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox7.setObjectName("checkBox7")
        self.SeatLayout.addWidget(self.checkBox7, 1, 1, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox8.setObjectName("checkBox8")
        self.SeatLayout.addWidget(self.checkBox8, 2, 1, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox25.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox25.setObjectName("checkBox25")
        self.SeatLayout.addWidget(self.checkBox25, 4, 4, 1, 1)
        self.checkBox26.raise_()
        self.checkBox4.raise_()
        self.checkBox14.raise_()
        self.checkBox3.raise_()
        self.checkBox21.raise_()
        self.checkBox17.raise_()
        self.checkBox11.raise_()
        self.checkBox10.raise_()
        self.checkBox9.raise_()
        self.checkBox2.raise_()
        self.checkBox27.raise_()
        self.checkBox29.raise_()
        self.checkBox19.raise_()
        self.checkBox24.raise_()
        self.checkBox6.raise_()
        self.checkBox13.raise_()
        self.checkBox30.raise_()
        self.checkBox22.raise_()
        self.checkBox28.raise_()
        self.checkBox18.raise_()
        self.checkBox15.raise_()
        self.checkBox8.raise_()
        self.checkBox1.raise_()
        self.checkBox16.raise_()
        self.checkBox23.raise_()
        self.checkBox20.raise_()
        self.checkBox12.raise_()
        self.checkBox5.raise_()
        self.checkBox7.raise_()
        self.checkBox25.raise_()
        self.ConfirmBeyonceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBeyonceBtn.setGeometry(QtCore.QRect(450, 930, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmBeyonceBtn.setFont(font)
        self.ConfirmBeyonceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmBeyonceBtn.setObjectName("ConfirmBeyonceBtn")
        self.BalanceNotEnoughMessage = QtWidgets.QLabel(self.centralwidget)
        self.BalanceNotEnoughMessage.setEnabled(False)
        self.BalanceNotEnoughMessage.setGeometry(QtCore.QRect(1130, 940, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BalanceNotEnoughMessage.setFont(font)
        self.BalanceNotEnoughMessage.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BalanceNotEnoughMessage.setText("")
        self.BalanceNotEnoughMessage.setObjectName("BalanceNotEnoughMessage")
        self.label.raise_()
        self.SeatBeyonceLabel.raise_()
        self.BeyonceBackBtn.raise_()
        self.DateBeyonceComboBox.raise_()
        self.BeyoncePriceLabel.raise_()
        self.DateBeyonceLabel.raise_()
        self.QuantityBeyonceLabel.raise_()
        self.QuantityCheckBtn.raise_()
        self.RowBeyonceLabel.raise_()
        self.RowBeyonceComboBox.raise_()
        self.TotalBeyonceLabel.raise_()
        self.TotalBeyonceLabelValue.raise_()
        self.PayBeyonceBtn.raise_()
        self.lineEdit.raise_()
        self.BeyonceBalanceLabel.raise_()
        self.gridLayoutWidget.raise_()
        self.ConfirmBeyonceBtn.raise_()
        self.BalanceNotEnoughMessage.raise_()
        BeyoncePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BeyoncePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        BeyoncePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BeyoncePage)
        self.statusbar.setObjectName("statusbar")
        BeyoncePage.setStatusBar(self.statusbar)

        self.retranslateUi(BeyoncePage)
        QtCore.QMetaObject.connectSlotsByName(BeyoncePage)

    def retranslateUi(self, BeyoncePage):
        _translate = QtCore.QCoreApplication.translate
        BeyoncePage.setWindowTitle(_translate("BeyoncePage", "MainWindow"))
        self.BeyonceBackBtn.setText(_translate("BeyoncePage", "<"))
        self.DateBeyonceComboBox.setItemText(0, _translate("BeyoncePage", "4 July - Washington, D.C. (Landover) @ Northwest Stadium"))
        self.DateBeyonceComboBox.setItemText(1, _translate("BeyoncePage", "7 July - Washington, D.C. (Landover) @ Northwest Stadium"))
        self.DateBeyonceComboBox.setItemText(2, _translate("BeyoncePage", "10 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(3, _translate("BeyoncePage", "11 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(4, _translate("BeyoncePage", "13 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(5, _translate("BeyoncePage", "14 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(6, _translate("BeyoncePage", "25 July -Las Vegas, NV @ Allegiant Stadium "))
        self.BeyoncePriceLabel.setText(_translate("BeyoncePage", "Price : 300$"))
        self.DateBeyonceLabel.setText(_translate("BeyoncePage", "Date & City"))
        self.QuantityBeyonceLabel.setText(_translate("BeyoncePage", "Quantity"))
        self.QuantityCheckBtn.setText(_translate("BeyoncePage", "✓"))
        self.RowBeyonceLabel.setText(_translate("BeyoncePage", "The Row"))
        self.SeatBeyonceLabel.setText(_translate("BeyoncePage", "The seat "))
        self.RowBeyonceComboBox.setItemText(0, _translate("BeyoncePage", "1"))
        self.RowBeyonceComboBox.setItemText(1, _translate("BeyoncePage", "2"))
        self.RowBeyonceComboBox.setItemText(2, _translate("BeyoncePage", "3"))
        self.RowBeyonceComboBox.setItemText(3, _translate("BeyoncePage", "4"))
        self.RowBeyonceComboBox.setItemText(4, _translate("BeyoncePage", "5"))
        self.RowBeyonceComboBox.setItemText(5, _translate("BeyoncePage", "6"))
        self.RowBeyonceComboBox.setItemText(6, _translate("BeyoncePage", "7"))
        self.RowBeyonceComboBox.setItemText(7, _translate("BeyoncePage", "8"))
        self.RowBeyonceComboBox.setItemText(8, _translate("BeyoncePage", "9"))
        self.RowBeyonceComboBox.setItemText(9, _translate("BeyoncePage", "10"))
        self.RowBeyonceComboBox.setItemText(10, _translate("BeyoncePage", "11"))
        self.RowBeyonceComboBox.setItemText(11, _translate("BeyoncePage", "12"))
        self.RowBeyonceComboBox.setItemText(12, _translate("BeyoncePage", "13"))
        self.RowBeyonceComboBox.setItemText(13, _translate("BeyoncePage", "14"))
        self.RowBeyonceComboBox.setItemText(14, _translate("BeyoncePage", "15"))
        self.RowBeyonceComboBox.setItemText(15, _translate("BeyoncePage", "16"))
        self.RowBeyonceComboBox.setItemText(16, _translate("BeyoncePage", "17"))
        self.RowBeyonceComboBox.setItemText(17, _translate("BeyoncePage", "18"))
        self.RowBeyonceComboBox.setItemText(18, _translate("BeyoncePage", "19"))
        self.RowBeyonceComboBox.setItemText(19, _translate("BeyoncePage", "20"))
        self.RowBeyonceComboBox.setItemText(20, _translate("BeyoncePage", "21"))
        self.RowBeyonceComboBox.setItemText(21, _translate("BeyoncePage", "22"))
        self.RowBeyonceComboBox.setItemText(22, _translate("BeyoncePage", "23"))
        self.RowBeyonceComboBox.setItemText(23, _translate("BeyoncePage", "24"))
        self.RowBeyonceComboBox.setItemText(24, _translate("BeyoncePage", "25"))
        self.RowBeyonceComboBox.setItemText(25, _translate("BeyoncePage", "26"))
        self.RowBeyonceComboBox.setItemText(26, _translate("BeyoncePage", "27"))
        self.RowBeyonceComboBox.setItemText(27, _translate("BeyoncePage", "28"))
        self.RowBeyonceComboBox.setItemText(28, _translate("BeyoncePage", "29"))
        self.RowBeyonceComboBox.setItemText(29, _translate("BeyoncePage", "30"))
        self.TotalBeyonceLabel.setText(_translate("BeyoncePage", "In Total"))
        self.TotalBeyonceLabelValue.setText(_translate("BeyoncePage", "0$"))
        self.PayBeyonceBtn.setText(_translate("BeyoncePage", "Check the Qiuantity first"))
        self.BeyonceBalanceLabel.setText(_translate("BeyoncePage", "Balance:"))
        self.checkBox26.setText(_translate("BeyoncePage", "26"))
        self.checkBox29.setText(_translate("BeyoncePage", "29"))
        self.checkBox19.setText(_translate("BeyoncePage", "19"))
        self.checkBox9.setText(_translate("BeyoncePage", "9"))
        self.checkBox24.setText(_translate("BeyoncePage", "24"))
        self.checkBox6.setText(_translate("BeyoncePage", "6"))
        self.checkBox22.setText(_translate("BeyoncePage", "22"))
        self.checkBox28.setText(_translate("BeyoncePage", "28"))
        self.checkBox17.setText(_translate("BeyoncePage", "17"))
        self.checkBox21.setText(_translate("BeyoncePage", "21"))
        self.checkBox13.setText(_translate("BeyoncePage", "13"))
        self.checkBox30.setText(_translate("BeyoncePage", "30"))
        self.checkBox11.setText(_translate("BeyoncePage", "11"))
        self.checkBox15.setText(_translate("BeyoncePage", "15"))
        self.checkBox16.setText(_translate("BeyoncePage", "16"))
        self.checkBox23.setText(_translate("BeyoncePage", "23"))
        self.checkBox1.setText(_translate("BeyoncePage", "1"))
        self.checkBox3.setText(_translate("BeyoncePage", "3"))
        self.checkBox20.setText(_translate("BeyoncePage", "20"))
        self.checkBox18.setText(_translate("BeyoncePage", "18"))
        self.checkBox2.setText(_translate("BeyoncePage", "2"))
        self.checkBox27.setText(_translate("BeyoncePage", "27"))
        self.checkBox4.setText(_translate("BeyoncePage", "4"))
        self.checkBox10.setText(_translate("BeyoncePage", "10"))
        self.checkBox14.setText(_translate("BeyoncePage", "14"))
        self.checkBox12.setText(_translate("BeyoncePage", "12"))
        self.checkBox5.setText(_translate("BeyoncePage", "5"))
        self.checkBox7.setText(_translate("BeyoncePage", "7"))
        self.checkBox8.setText(_translate("BeyoncePage", "8"))
        self.checkBox25.setText(_translate("BeyoncePage", "25"))
        self.ConfirmBeyonceBtn.setText(_translate("BeyoncePage", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BeyoncePage = QtWidgets.QMainWindow()
    ui = Ui_BeyoncePage()
    ui.setupUi(BeyoncePage)
    BeyoncePage.show()
    sys.exit(app.exec_())
