# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\BilliePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BilleiPage(object):
    def setupUi(self, BilleiPage):
        BilleiPage.setObjectName("BilleiPage")
        BilleiPage.resize(1920, 1080)
        BilleiPage.setMinimumSize(QtCore.QSize(1920, 1080))
        BilleiPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(BilleiPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\BilliePage.png"))
        self.label.setObjectName("label")
        self.BillieBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BillieBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.BillieBackBtn.setFont(font)
        self.BillieBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BillieBackBtn.setObjectName("BillieBackBtn")
        self.DateBillieComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateBillieComboBox.setGeometry(QtCore.QRect(330, 560, 361, 41))
        self.DateBillieComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateBillieComboBox.setObjectName("DateBillieComboBox")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.BilliePriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BilliePriceLabel.setGeometry(QtCore.QRect(70, 490, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BilliePriceLabel.setFont(font)
        self.BilliePriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BilliePriceLabel.setObjectName("BilliePriceLabel")
        self.DateBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateBillieLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateBillieLabel.setFont(font)
        self.DateBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateBillieLabel.setObjectName("DateBillieLabel")
        self.QuantityBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityBillieLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityBillieLabel.setFont(font)
        self.QuantityBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityBillieLabel.setObjectName("QuantityBillieLabel")
        self.ConfirmBillieBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBillieBtn.setGeometry(QtCore.QRect(450, 930, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmBillieBtn.setFont(font)
        self.ConfirmBillieBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmBillieBtn.setObjectName("ConfirmBillieBtn")
        self.RowBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowBillieLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowBillieLabel.setFont(font)
        self.RowBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowBillieLabel.setObjectName("RowBillieLabel")
        self.SeatBilieLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatBilieLabel.setGeometry(QtCore.QRect(70, 740, 621, 121))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatBilieLabel.setFont(font)
        self.SeatBilieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatBilieLabel.setObjectName("SeatBilieLabel")
        self.RowBillieComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowBillieComboBox.setGeometry(QtCore.QRect(330, 680, 361, 41))
        self.RowBillieComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowBillieComboBox.setObjectName("RowBillieComboBox")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.TotalBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalBillieLabel.setGeometry(QtCore.QRect(160, 870, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBillieLabel.setFont(font)
        self.TotalBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBillieLabel.setObjectName("TotalBillieLabel")
        self.TotalBillieLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalBillieLabelValue.setGeometry(QtCore.QRect(340, 870, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBillieLabelValue.setFont(font)
        self.TotalBillieLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBillieLabelValue.setObjectName("TotalBillieLabelValue")
        self.PayBillieBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayBillieBtn.setEnabled(False)
        self.PayBillieBtn.setGeometry(QtCore.QRect(1470, 940, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayBillieBtn.setFont(font)
        self.PayBillieBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayBillieBtn.setObjectName("PayBillieBtn")
        self.BillieQuantityLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.BillieQuantityLabel.setGeometry(QtCore.QRect(330, 620, 361, 41))
        self.BillieQuantityLabel.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.BillieQuantityLabel.setObjectName("BillieQuantityLabel")
        self.BillieBalanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillieBalanceLabel.setGeometry(QtCore.QRect(330, 490, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillieBalanceLabel.setFont(font)
        self.BillieBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillieBalanceLabel.setObjectName("BillieBalanceLabel")
        self.QuantityCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QuantityCheckBtn.setGeometry(QtCore.QRect(710, 810, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityCheckBtn.setFont(font)
        self.QuantityCheckBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.QuantityCheckBtn.setObjectName("QuantityCheckBtn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 740, 361, 130))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SeatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SeatLayout.setContentsMargins(0, 0, 0, 0)
        self.SeatLayout.setObjectName("SeatLayout")
        self.checkBox26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox26.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox26.setObjectName("checkBox26")
        self.SeatLayout.addWidget(self.checkBox26, 0, 5, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox29.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox29.setObjectName("checkBox29")
        self.SeatLayout.addWidget(self.checkBox29, 3, 5, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox19.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox19.setObjectName("checkBox19")
        self.SeatLayout.addWidget(self.checkBox19, 3, 3, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox9.setObjectName("checkBox9")
        self.SeatLayout.addWidget(self.checkBox9, 3, 1, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox24.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox24.setObjectName("checkBox24")
        self.SeatLayout.addWidget(self.checkBox24, 3, 4, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox6.setObjectName("checkBox6")
        self.SeatLayout.addWidget(self.checkBox6, 0, 1, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox22.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox22.setObjectName("checkBox22")
        self.SeatLayout.addWidget(self.checkBox22, 1, 4, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox28.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox28.setObjectName("checkBox28")
        self.SeatLayout.addWidget(self.checkBox28, 2, 5, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox17.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox17.setObjectName("checkBox17")
        self.SeatLayout.addWidget(self.checkBox17, 1, 3, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox21.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox21.setObjectName("checkBox21")
        self.SeatLayout.addWidget(self.checkBox21, 0, 4, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox13.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox13.setObjectName("checkBox13")
        self.SeatLayout.addWidget(self.checkBox13, 2, 2, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox30.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox30.setObjectName("checkBox30")
        self.SeatLayout.addWidget(self.checkBox30, 4, 5, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox11.setObjectName("checkBox11")
        self.SeatLayout.addWidget(self.checkBox11, 0, 2, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox15.setObjectName("checkBox15")
        self.SeatLayout.addWidget(self.checkBox15, 4, 2, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox16.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox16.setObjectName("checkBox16")
        self.SeatLayout.addWidget(self.checkBox16, 0, 3, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox23.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox23.setObjectName("checkBox23")
        self.SeatLayout.addWidget(self.checkBox23, 2, 4, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox1.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox1.setObjectName("checkBox1")
        self.SeatLayout.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox3.setObjectName("checkBox3")
        self.SeatLayout.addWidget(self.checkBox3, 2, 0, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox20.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox20.setObjectName("checkBox20")
        self.SeatLayout.addWidget(self.checkBox20, 4, 3, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox18.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox18.setObjectName("checkBox18")
        self.SeatLayout.addWidget(self.checkBox18, 2, 3, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox2.setObjectName("checkBox2")
        self.SeatLayout.addWidget(self.checkBox2, 1, 0, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox27.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox27.setObjectName("checkBox27")
        self.SeatLayout.addWidget(self.checkBox27, 1, 5, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox4.setObjectName("checkBox4")
        self.SeatLayout.addWidget(self.checkBox4, 3, 0, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox10.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox10.setObjectName("checkBox10")
        self.SeatLayout.addWidget(self.checkBox10, 4, 1, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox14.setObjectName("checkBox14")
        self.SeatLayout.addWidget(self.checkBox14, 3, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox12.setObjectName("checkBox12")
        self.SeatLayout.addWidget(self.checkBox12, 1, 2, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox5.setObjectName("checkBox5")
        self.SeatLayout.addWidget(self.checkBox5, 4, 0, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox7.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox7.setObjectName("checkBox7")
        self.SeatLayout.addWidget(self.checkBox7, 1, 1, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox8.setObjectName("checkBox8")
        self.SeatLayout.addWidget(self.checkBox8, 2, 1, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox25.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox25.setObjectName("checkBox25")
        self.SeatLayout.addWidget(self.checkBox25, 4, 4, 1, 1)
        self.checkBox26.raise_()
        self.checkBox4.raise_()
        self.checkBox14.raise_()
        self.checkBox3.raise_()
        self.checkBox21.raise_()
        self.checkBox17.raise_()
        self.checkBox11.raise_()
        self.checkBox10.raise_()
        self.checkBox9.raise_()
        self.checkBox2.raise_()
        self.checkBox27.raise_()
        self.checkBox29.raise_()
        self.checkBox19.raise_()
        self.checkBox24.raise_()
        self.checkBox6.raise_()
        self.checkBox13.raise_()
        self.checkBox30.raise_()
        self.checkBox22.raise_()
        self.checkBox28.raise_()
        self.checkBox18.raise_()
        self.checkBox15.raise_()
        self.checkBox8.raise_()
        self.checkBox1.raise_()
        self.checkBox16.raise_()
        self.checkBox23.raise_()
        self.checkBox20.raise_()
        self.checkBox12.raise_()
        self.checkBox5.raise_()
        self.checkBox7.raise_()
        self.checkBox25.raise_()
        self.BalanceNotEnoughMessage = QtWidgets.QLabel(self.centralwidget)
        self.BalanceNotEnoughMessage.setEnabled(False)
        self.BalanceNotEnoughMessage.setGeometry(QtCore.QRect(1140, 940, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BalanceNotEnoughMessage.setFont(font)
        self.BalanceNotEnoughMessage.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BalanceNotEnoughMessage.setText("")
        self.BalanceNotEnoughMessage.setObjectName("BalanceNotEnoughMessage")
        BilleiPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BilleiPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        BilleiPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BilleiPage)
        self.statusbar.setObjectName("statusbar")
        BilleiPage.setStatusBar(self.statusbar)

        self.retranslateUi(BilleiPage)
        QtCore.QMetaObject.connectSlotsByName(BilleiPage)

    def retranslateUi(self, BilleiPage):
        _translate = QtCore.QCoreApplication.translate
        BilleiPage.setWindowTitle(_translate("BilleiPage", "MainWindow"))
        self.BillieBackBtn.setText(_translate("BilleiPage", "<"))
        self.DateBillieComboBox.setItemText(0, _translate("BilleiPage", "8 July - Glasgow - OVO Hydro"))
        self.DateBillieComboBox.setItemText(1, _translate("BilleiPage", "10 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(2, _translate("BilleiPage", "11 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(3, _translate("BilleiPage", "13 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(4, _translate("BilleiPage", "14 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(5, _translate("BilleiPage", "16 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(6, _translate("BilleiPage", "17 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(7, _translate("BilleiPage", "19 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(8, _translate("BilleiPage", "20 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(9, _translate("BilleiPage", "22 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(10, _translate("BilleiPage", "23 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(11, _translate("BilleiPage", "26 July - Dublin - 3Arena"))
        self.DateBillieComboBox.setItemText(12, _translate("BilleiPage", "27 July - Dublin - 3Arena"))
        self.DateBillieComboBox.setItemText(13, _translate("BilleiPage", "16 August -Saitma(Tokyo) -  Saitama Super Arena"))
        self.DateBillieComboBox.setItemText(14, _translate("BilleiPage", "17 August -Saitma(Tokyo) -  Saitama Super Arena"))
        self.DateBillieComboBox.setItemText(15, _translate("BilleiPage", "9 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(16, _translate("BilleiPage", "11 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(17, _translate("BilleiPage", "12 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(18, _translate("BilleiPage", "14 Octomber - Orlando - Kia Center"))
        self.DateBillieComboBox.setItemText(19, _translate("BilleiPage", "16 Octomber - Raleigh - Lenovo Center"))
        self.DateBillieComboBox.setItemText(20, _translate("BilleiPage", "17 Octomber - Raleigh - Lenovo Center"))
        self.DateBillieComboBox.setItemText(21, _translate("BilleiPage", "19 Octomber - Charlotte -Spectrum Center"))
        self.DateBillieComboBox.setItemText(22, _translate("BilleiPage", "20 Octomber - Charlotte -Spectrum Center"))
        self.DateBillieComboBox.setItemText(23, _translate("BilleiPage", "23 Octomber - Philadelphia - Wells Frago Center"))
        self.DateBillieComboBox.setItemText(24, _translate("BilleiPage", "25 Octomber - Elmont -UBS arena"))
        self.DateBillieComboBox.setItemText(25, _translate("BilleiPage", "26 Octomber - Elmont -UBS arena"))
        self.DateBillieComboBox.setItemText(26, _translate("BilleiPage", "7 November  - New Orleans - Smothie Kind Center"))
        self.DateBillieComboBox.setItemText(27, _translate("BilleiPage", "8 November  - New Orleans - Smothie Kind Center"))
        self.DateBillieComboBox.setItemText(28, _translate("BilleiPage", "10 November - Tulsa - BOK Center"))
        self.DateBillieComboBox.setItemText(29, _translate("BilleiPage", "11 November - Tulsa - BOK Center"))
        self.DateBillieComboBox.setItemText(30, _translate("BilleiPage", "13 November - Austin - Moddy Center ATX"))
        self.DateBillieComboBox.setItemText(31, _translate("BilleiPage", "14 November - Austin - Moddy Center ATX"))
        self.DateBillieComboBox.setItemText(32, _translate("BilleiPage", "18 November - Phoenix -PHX Arena"))
        self.DateBillieComboBox.setItemText(33, _translate("BilleiPage", "19 November - Phoenix -PHX Arena"))
        self.DateBillieComboBox.setItemText(34, _translate("BilleiPage", "22 November -San Francisco - Chase Center"))
        self.DateBillieComboBox.setItemText(35, _translate("BilleiPage", "23 November -San Francisco - Chase Center"))
        self.BilliePriceLabel.setText(_translate("BilleiPage", "Price : 200$"))
        self.DateBillieLabel.setText(_translate("BilleiPage", "Date & City"))
        self.QuantityBillieLabel.setText(_translate("BilleiPage", "Quantity"))
        self.ConfirmBillieBtn.setText(_translate("BilleiPage", "Confirm "))
        self.RowBillieLabel.setText(_translate("BilleiPage", "The Row"))
        self.SeatBilieLabel.setText(_translate("BilleiPage", "The seat"))
        self.RowBillieComboBox.setItemText(0, _translate("BilleiPage", "1"))
        self.RowBillieComboBox.setItemText(1, _translate("BilleiPage", "2"))
        self.RowBillieComboBox.setItemText(2, _translate("BilleiPage", "3"))
        self.RowBillieComboBox.setItemText(3, _translate("BilleiPage", "4"))
        self.RowBillieComboBox.setItemText(4, _translate("BilleiPage", "5"))
        self.RowBillieComboBox.setItemText(5, _translate("BilleiPage", "6"))
        self.RowBillieComboBox.setItemText(6, _translate("BilleiPage", "7"))
        self.RowBillieComboBox.setItemText(7, _translate("BilleiPage", "8"))
        self.RowBillieComboBox.setItemText(8, _translate("BilleiPage", "9"))
        self.RowBillieComboBox.setItemText(9, _translate("BilleiPage", "10"))
        self.RowBillieComboBox.setItemText(10, _translate("BilleiPage", "11"))
        self.RowBillieComboBox.setItemText(11, _translate("BilleiPage", "12"))
        self.RowBillieComboBox.setItemText(12, _translate("BilleiPage", "13"))
        self.RowBillieComboBox.setItemText(13, _translate("BilleiPage", "14"))
        self.RowBillieComboBox.setItemText(14, _translate("BilleiPage", "15"))
        self.RowBillieComboBox.setItemText(15, _translate("BilleiPage", "16"))
        self.RowBillieComboBox.setItemText(16, _translate("BilleiPage", "17"))
        self.RowBillieComboBox.setItemText(17, _translate("BilleiPage", "18"))
        self.RowBillieComboBox.setItemText(18, _translate("BilleiPage", "19"))
        self.RowBillieComboBox.setItemText(19, _translate("BilleiPage", "20"))
        self.RowBillieComboBox.setItemText(20, _translate("BilleiPage", "21"))
        self.RowBillieComboBox.setItemText(21, _translate("BilleiPage", "22"))
        self.RowBillieComboBox.setItemText(22, _translate("BilleiPage", "23"))
        self.RowBillieComboBox.setItemText(23, _translate("BilleiPage", "24"))
        self.RowBillieComboBox.setItemText(24, _translate("BilleiPage", "25"))
        self.RowBillieComboBox.setItemText(25, _translate("BilleiPage", "26"))
        self.RowBillieComboBox.setItemText(26, _translate("BilleiPage", "27"))
        self.RowBillieComboBox.setItemText(27, _translate("BilleiPage", "28"))
        self.RowBillieComboBox.setItemText(28, _translate("BilleiPage", "29"))
        self.RowBillieComboBox.setItemText(29, _translate("BilleiPage", "30"))
        self.TotalBillieLabel.setText(_translate("BilleiPage", "In Total"))
        self.TotalBillieLabelValue.setText(_translate("BilleiPage", "0$"))
        self.PayBillieBtn.setText(_translate("BilleiPage", "Choose The Quantity First"))
        self.BillieBalanceLabel.setText(_translate("BilleiPage", "Balance:"))
        self.QuantityCheckBtn.setText(_translate("BilleiPage", "✓"))
        self.checkBox26.setText(_translate("BilleiPage", "26"))
        self.checkBox29.setText(_translate("BilleiPage", "29"))
        self.checkBox19.setText(_translate("BilleiPage", "19"))
        self.checkBox9.setText(_translate("BilleiPage", "9"))
        self.checkBox24.setText(_translate("BilleiPage", "24"))
        self.checkBox6.setText(_translate("BilleiPage", "6"))
        self.checkBox22.setText(_translate("BilleiPage", "22"))
        self.checkBox28.setText(_translate("BilleiPage", "28"))
        self.checkBox17.setText(_translate("BilleiPage", "17"))
        self.checkBox21.setText(_translate("BilleiPage", "21"))
        self.checkBox13.setText(_translate("BilleiPage", "13"))
        self.checkBox30.setText(_translate("BilleiPage", "30"))
        self.checkBox11.setText(_translate("BilleiPage", "11"))
        self.checkBox15.setText(_translate("BilleiPage", "15"))
        self.checkBox16.setText(_translate("BilleiPage", "16"))
        self.checkBox23.setText(_translate("BilleiPage", "23"))
        self.checkBox1.setText(_translate("BilleiPage", "1"))
        self.checkBox3.setText(_translate("BilleiPage", "3"))
        self.checkBox20.setText(_translate("BilleiPage", "20"))
        self.checkBox18.setText(_translate("BilleiPage", "18"))
        self.checkBox2.setText(_translate("BilleiPage", "2"))
        self.checkBox27.setText(_translate("BilleiPage", "27"))
        self.checkBox4.setText(_translate("BilleiPage", "4"))
        self.checkBox10.setText(_translate("BilleiPage", "10"))
        self.checkBox14.setText(_translate("BilleiPage", "14"))
        self.checkBox12.setText(_translate("BilleiPage", "12"))
        self.checkBox5.setText(_translate("BilleiPage", "5"))
        self.checkBox7.setText(_translate("BilleiPage", "7"))
        self.checkBox8.setText(_translate("BilleiPage", "8"))
        self.checkBox25.setText(_translate("BilleiPage", "25"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BilleiPage = QtWidgets.QMainWindow()
    ui = Ui_BilleiPage()
    ui.setupUi(BilleiPage)
    BilleiPage.show()
    sys.exit(app.exec_())
