# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\LanaPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LanaPage(object):
    def setupUi(self, LanaPage):
        LanaPage.setObjectName("LanaPage")
        LanaPage.resize(1920, 1080)
        LanaPage.setMinimumSize(QtCore.QSize(1920, 1080))
        LanaPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(LanaPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\LanaPage.png"))
        self.label.setObjectName("label")
        self.LanaBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LanaBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.LanaBackBtn.setFont(font)
        self.LanaBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.LanaBackBtn.setObjectName("LanaBackBtn")
        self.DateLanaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateLanaComboBox.setGeometry(QtCore.QRect(330, 560, 311, 41))
        self.DateLanaComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateLanaComboBox.setObjectName("DateLanaComboBox")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.LanaPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.LanaPriceLabel.setGeometry(QtCore.QRect(70, 500, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LanaPriceLabel.setFont(font)
        self.LanaPriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.LanaPriceLabel.setObjectName("LanaPriceLabel")
        self.DateLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateLanaLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateLanaLabel.setFont(font)
        self.DateLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateLanaLabel.setObjectName("DateLanaLabel")
        self.QuantityLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityLanaLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityLanaLabel.setFont(font)
        self.QuantityLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityLanaLabel.setObjectName("QuantityLanaLabel")
        self.ConfirmLanaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmLanaBtn.setGeometry(QtCore.QRect(450, 940, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmLanaBtn.setFont(font)
        self.ConfirmLanaBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmLanaBtn.setObjectName("ConfirmLanaBtn")
        self.RowLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowLanaLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowLanaLabel.setFont(font)
        self.RowLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowLanaLabel.setObjectName("RowLanaLabel")
        self.SeatLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatLanaLabel.setGeometry(QtCore.QRect(70, 740, 571, 131))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatLanaLabel.setFont(font)
        self.SeatLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatLanaLabel.setObjectName("SeatLanaLabel")
        self.RowLanaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowLanaComboBox.setGeometry(QtCore.QRect(330, 680, 311, 41))
        self.RowLanaComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowLanaComboBox.setObjectName("RowLanaComboBox")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.TotalLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalLanaLabel.setGeometry(QtCore.QRect(150, 880, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalLanaLabel.setFont(font)
        self.TotalLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalLanaLabel.setObjectName("TotalLanaLabel")
        self.TotalLanaLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalLanaLabelValue.setGeometry(QtCore.QRect(330, 880, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalLanaLabelValue.setFont(font)
        self.TotalLanaLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalLanaLabelValue.setObjectName("TotalLanaLabelValue")
        self.PayLanaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayLanaBtn.setEnabled(False)
        self.PayLanaBtn.setGeometry(QtCore.QRect(1470, 940, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayLanaBtn.setFont(font)
        self.PayLanaBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayLanaBtn.setObjectName("PayLanaBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 311, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.LanaBalanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.LanaBalanceLabel.setGeometry(QtCore.QRect(330, 500, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LanaBalanceLabel.setFont(font)
        self.LanaBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.LanaBalanceLabel.setObjectName("LanaBalanceLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 740, 311, 130))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SeatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SeatLayout.setContentsMargins(0, 0, 0, 0)
        self.SeatLayout.setObjectName("SeatLayout")
        self.checkBox26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox26.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox26.setObjectName("checkBox26")
        self.SeatLayout.addWidget(self.checkBox26, 0, 5, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox29.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox29.setObjectName("checkBox29")
        self.SeatLayout.addWidget(self.checkBox29, 3, 5, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox19.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox19.setObjectName("checkBox19")
        self.SeatLayout.addWidget(self.checkBox19, 3, 3, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox9.setObjectName("checkBox9")
        self.SeatLayout.addWidget(self.checkBox9, 3, 1, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox24.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox24.setObjectName("checkBox24")
        self.SeatLayout.addWidget(self.checkBox24, 3, 4, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox6.setObjectName("checkBox6")
        self.SeatLayout.addWidget(self.checkBox6, 0, 1, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox22.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox22.setObjectName("checkBox22")
        self.SeatLayout.addWidget(self.checkBox22, 1, 4, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox28.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox28.setObjectName("checkBox28")
        self.SeatLayout.addWidget(self.checkBox28, 2, 5, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox17.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox17.setObjectName("checkBox17")
        self.SeatLayout.addWidget(self.checkBox17, 1, 3, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox21.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox21.setObjectName("checkBox21")
        self.SeatLayout.addWidget(self.checkBox21, 0, 4, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox13.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox13.setObjectName("checkBox13")
        self.SeatLayout.addWidget(self.checkBox13, 2, 2, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox30.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox30.setObjectName("checkBox30")
        self.SeatLayout.addWidget(self.checkBox30, 4, 5, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox11.setObjectName("checkBox11")
        self.SeatLayout.addWidget(self.checkBox11, 0, 2, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox15.setObjectName("checkBox15")
        self.SeatLayout.addWidget(self.checkBox15, 4, 2, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox16.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox16.setObjectName("checkBox16")
        self.SeatLayout.addWidget(self.checkBox16, 0, 3, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox23.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox23.setObjectName("checkBox23")
        self.SeatLayout.addWidget(self.checkBox23, 2, 4, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox1.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox1.setObjectName("checkBox1")
        self.SeatLayout.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox3.setObjectName("checkBox3")
        self.SeatLayout.addWidget(self.checkBox3, 2, 0, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox20.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox20.setObjectName("checkBox20")
        self.SeatLayout.addWidget(self.checkBox20, 4, 3, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox18.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox18.setObjectName("checkBox18")
        self.SeatLayout.addWidget(self.checkBox18, 2, 3, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox2.setObjectName("checkBox2")
        self.SeatLayout.addWidget(self.checkBox2, 1, 0, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox27.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox27.setObjectName("checkBox27")
        self.SeatLayout.addWidget(self.checkBox27, 1, 5, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox4.setObjectName("checkBox4")
        self.SeatLayout.addWidget(self.checkBox4, 3, 0, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox10.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox10.setObjectName("checkBox10")
        self.SeatLayout.addWidget(self.checkBox10, 4, 1, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox14.setObjectName("checkBox14")
        self.SeatLayout.addWidget(self.checkBox14, 3, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox12.setObjectName("checkBox12")
        self.SeatLayout.addWidget(self.checkBox12, 1, 2, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox5.setObjectName("checkBox5")
        self.SeatLayout.addWidget(self.checkBox5, 4, 0, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox7.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox7.setObjectName("checkBox7")
        self.SeatLayout.addWidget(self.checkBox7, 1, 1, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox8.setObjectName("checkBox8")
        self.SeatLayout.addWidget(self.checkBox8, 2, 1, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox25.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox25.setObjectName("checkBox25")
        self.SeatLayout.addWidget(self.checkBox25, 4, 4, 1, 1)
        self.checkBox26.raise_()
        self.checkBox4.raise_()
        self.checkBox14.raise_()
        self.checkBox3.raise_()
        self.checkBox21.raise_()
        self.checkBox17.raise_()
        self.checkBox11.raise_()
        self.checkBox10.raise_()
        self.checkBox9.raise_()
        self.checkBox2.raise_()
        self.checkBox27.raise_()
        self.checkBox29.raise_()
        self.checkBox19.raise_()
        self.checkBox24.raise_()
        self.checkBox6.raise_()
        self.checkBox13.raise_()
        self.checkBox30.raise_()
        self.checkBox22.raise_()
        self.checkBox28.raise_()
        self.checkBox18.raise_()
        self.checkBox15.raise_()
        self.checkBox8.raise_()
        self.checkBox1.raise_()
        self.checkBox16.raise_()
        self.checkBox23.raise_()
        self.checkBox20.raise_()
        self.checkBox12.raise_()
        self.checkBox5.raise_()
        self.checkBox7.raise_()
        self.checkBox25.raise_()
        self.QuantityCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QuantityCheckBtn.setGeometry(QtCore.QRect(660, 820, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityCheckBtn.setFont(font)
        self.QuantityCheckBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.QuantityCheckBtn.setObjectName("QuantityCheckBtn")
        self.BalanceNotEnoughMessage = QtWidgets.QLabel(self.centralwidget)
        self.BalanceNotEnoughMessage.setEnabled(False)
        self.BalanceNotEnoughMessage.setGeometry(QtCore.QRect(1470, 860, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BalanceNotEnoughMessage.setFont(font)
        self.BalanceNotEnoughMessage.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BalanceNotEnoughMessage.setText("")
        self.BalanceNotEnoughMessage.setObjectName("BalanceNotEnoughMessage")
        LanaPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LanaPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        LanaPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LanaPage)
        self.statusbar.setObjectName("statusbar")
        LanaPage.setStatusBar(self.statusbar)

        self.retranslateUi(LanaPage)
        QtCore.QMetaObject.connectSlotsByName(LanaPage)

    def retranslateUi(self, LanaPage):
        _translate = QtCore.QCoreApplication.translate
        LanaPage.setWindowTitle(_translate("LanaPage", "MainWindow"))
        self.LanaBackBtn.setText(_translate("LanaPage", "<"))
        self.DateLanaComboBox.setItemText(0, _translate("LanaPage", "23 June - Cardiff - Principality Stadium"))
        self.DateLanaComboBox.setItemText(1, _translate("LanaPage", "26 June - Glasgow - Hampden Park"))
        self.DateLanaComboBox.setItemText(2, _translate("LanaPage", "28 June - Liverpool - Anfield Stadium"))
        self.DateLanaComboBox.setItemText(3, _translate("LanaPage", "30 June - Dublin - Aviva Stadium"))
        self.DateLanaComboBox.setItemText(4, _translate("LanaPage", "3 July - London - Wembley Staidum"))
        self.DateLanaComboBox.setItemText(5, _translate("LanaPage", "4 July - London - Wembley Staidum"))
        self.LanaPriceLabel.setText(_translate("LanaPage", "Price : 180$"))
        self.DateLanaLabel.setText(_translate("LanaPage", "Date & City"))
        self.QuantityLanaLabel.setText(_translate("LanaPage", "Quantity"))
        self.ConfirmLanaBtn.setText(_translate("LanaPage", "Confirm "))
        self.RowLanaLabel.setText(_translate("LanaPage", "The Row"))
        self.SeatLanaLabel.setText(_translate("LanaPage", "The seat"))
        self.RowLanaComboBox.setItemText(0, _translate("LanaPage", "1"))
        self.RowLanaComboBox.setItemText(1, _translate("LanaPage", "2"))
        self.RowLanaComboBox.setItemText(2, _translate("LanaPage", "3"))
        self.RowLanaComboBox.setItemText(3, _translate("LanaPage", "4"))
        self.RowLanaComboBox.setItemText(4, _translate("LanaPage", "5"))
        self.RowLanaComboBox.setItemText(5, _translate("LanaPage", "6"))
        self.RowLanaComboBox.setItemText(6, _translate("LanaPage", "7"))
        self.RowLanaComboBox.setItemText(7, _translate("LanaPage", "8"))
        self.RowLanaComboBox.setItemText(8, _translate("LanaPage", "9"))
        self.RowLanaComboBox.setItemText(9, _translate("LanaPage", "10"))
        self.RowLanaComboBox.setItemText(10, _translate("LanaPage", "11"))
        self.RowLanaComboBox.setItemText(11, _translate("LanaPage", "12"))
        self.RowLanaComboBox.setItemText(12, _translate("LanaPage", "13"))
        self.RowLanaComboBox.setItemText(13, _translate("LanaPage", "14"))
        self.RowLanaComboBox.setItemText(14, _translate("LanaPage", "15"))
        self.RowLanaComboBox.setItemText(15, _translate("LanaPage", "16"))
        self.RowLanaComboBox.setItemText(16, _translate("LanaPage", "17"))
        self.RowLanaComboBox.setItemText(17, _translate("LanaPage", "18"))
        self.RowLanaComboBox.setItemText(18, _translate("LanaPage", "19"))
        self.RowLanaComboBox.setItemText(19, _translate("LanaPage", "20"))
        self.RowLanaComboBox.setItemText(20, _translate("LanaPage", "21"))
        self.RowLanaComboBox.setItemText(21, _translate("LanaPage", "22"))
        self.RowLanaComboBox.setItemText(22, _translate("LanaPage", "23"))
        self.RowLanaComboBox.setItemText(23, _translate("LanaPage", "24"))
        self.RowLanaComboBox.setItemText(24, _translate("LanaPage", "25"))
        self.RowLanaComboBox.setItemText(25, _translate("LanaPage", "26"))
        self.RowLanaComboBox.setItemText(26, _translate("LanaPage", "27"))
        self.RowLanaComboBox.setItemText(27, _translate("LanaPage", "28"))
        self.RowLanaComboBox.setItemText(28, _translate("LanaPage", "29"))
        self.RowLanaComboBox.setItemText(29, _translate("LanaPage", "30"))
        self.TotalLanaLabel.setText(_translate("LanaPage", "In Total"))
        self.TotalLanaLabelValue.setText(_translate("LanaPage", "0$"))
        self.PayLanaBtn.setText(_translate("LanaPage", "Choose The Quantity First"))
        self.LanaBalanceLabel.setText(_translate("LanaPage", "Balance:"))
        self.checkBox26.setText(_translate("LanaPage", "26"))
        self.checkBox29.setText(_translate("LanaPage", "29"))
        self.checkBox19.setText(_translate("LanaPage", "19"))
        self.checkBox9.setText(_translate("LanaPage", "9"))
        self.checkBox24.setText(_translate("LanaPage", "24"))
        self.checkBox6.setText(_translate("LanaPage", "6"))
        self.checkBox22.setText(_translate("LanaPage", "22"))
        self.checkBox28.setText(_translate("LanaPage", "28"))
        self.checkBox17.setText(_translate("LanaPage", "17"))
        self.checkBox21.setText(_translate("LanaPage", "21"))
        self.checkBox13.setText(_translate("LanaPage", "13"))
        self.checkBox30.setText(_translate("LanaPage", "30"))
        self.checkBox11.setText(_translate("LanaPage", "11"))
        self.checkBox15.setText(_translate("LanaPage", "15"))
        self.checkBox16.setText(_translate("LanaPage", "16"))
        self.checkBox23.setText(_translate("LanaPage", "23"))
        self.checkBox1.setText(_translate("LanaPage", "1"))
        self.checkBox3.setText(_translate("LanaPage", "3"))
        self.checkBox20.setText(_translate("LanaPage", "20"))
        self.checkBox18.setText(_translate("LanaPage", "18"))
        self.checkBox2.setText(_translate("LanaPage", "2"))
        self.checkBox27.setText(_translate("LanaPage", "27"))
        self.checkBox4.setText(_translate("LanaPage", "4"))
        self.checkBox10.setText(_translate("LanaPage", "10"))
        self.checkBox14.setText(_translate("LanaPage", "14"))
        self.checkBox12.setText(_translate("LanaPage", "12"))
        self.checkBox5.setText(_translate("LanaPage", "5"))
        self.checkBox7.setText(_translate("LanaPage", "7"))
        self.checkBox8.setText(_translate("LanaPage", "8"))
        self.checkBox25.setText(_translate("LanaPage", "25"))
        self.QuantityCheckBtn.setText(_translate("LanaPage", "✓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LanaPage = QtWidgets.QMainWindow()
    ui = Ui_LanaPage()
    ui.setupUi(LanaPage)
    LanaPage.show()
    sys.exit(app.exec_())
