# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\RecomendationsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecPage(object):
    def setupUi(self, RecPage):
        RecPage.setObjectName("RecPage")
        RecPage.resize(1920, 1080)
        RecPage.setMinimumSize(QtCore.QSize(1920, 1080))
        RecPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(RecPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, -20, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\RecPagePic.png"))
        self.label.setObjectName("label")
        self.RecBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RecBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.RecBackBtn.setFont(font)
        self.RecBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RecBackBtn.setObjectName("RecBackBtn")
        self.GenerateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateBtn.setGeometry(QtCore.QRect(430, 400, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.GenerateBtn.setFont(font)
        self.GenerateBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.GenerateBtn.setObjectName("GenerateBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 300, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1040, 300, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Rec1LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Rec1LabelSong.setGeometry(QtCore.QRect(240, 520, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec1LabelSong.setFont(font)
        self.Rec1LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec1LabelSong.setText("")
        self.Rec1LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec1LabelSong.setObjectName("Rec1LabelSong")
        self.Rec2LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Rec2LabelSong.setGeometry(QtCore.QRect(240, 590, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec2LabelSong.setFont(font)
        self.Rec2LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec2LabelSong.setText("")
        self.Rec2LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec2LabelSong.setObjectName("Rec2LabelSong")
        self.Rec3LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Rec3LabelSong.setGeometry(QtCore.QRect(240, 660, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec3LabelSong.setFont(font)
        self.Rec3LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec3LabelSong.setText("")
        self.Rec3LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec3LabelSong.setObjectName("Rec3LabelSong")
        self.Rec4LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Rec4LabelSong.setGeometry(QtCore.QRect(240, 730, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec4LabelSong.setFont(font)
        self.Rec4LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec4LabelSong.setText("")
        self.Rec4LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec4LabelSong.setObjectName("Rec4LabelSong")
        self.Rec5LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Rec5LabelSong.setGeometry(QtCore.QRect(240, 800, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec5LabelSong.setFont(font)
        self.Rec5LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec5LabelSong.setText("")
        self.Rec5LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec5LabelSong.setObjectName("Rec5LabelSong")
        self.Rec1Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Rec1Labelartist.setGeometry(QtCore.QRect(630, 550, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec1Labelartist.setFont(font)
        self.Rec1Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec1Labelartist.setText("")
        self.Rec1Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec1Labelartist.setObjectName("Rec1Labelartist")
        self.Rec2Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Rec2Labelartist.setGeometry(QtCore.QRect(630, 620, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec2Labelartist.setFont(font)
        self.Rec2Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec2Labelartist.setText("")
        self.Rec2Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec2Labelartist.setObjectName("Rec2Labelartist")
        self.Rec3Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Rec3Labelartist.setGeometry(QtCore.QRect(630, 690, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec3Labelartist.setFont(font)
        self.Rec3Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec3Labelartist.setText("")
        self.Rec3Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec3Labelartist.setObjectName("Rec3Labelartist")
        self.Rec4Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Rec4Labelartist.setGeometry(QtCore.QRect(630, 760, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec4Labelartist.setFont(font)
        self.Rec4Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec4Labelartist.setText("")
        self.Rec4Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec4Labelartist.setObjectName("Rec4Labelartist")
        self.Rec5Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Rec5Labelartist.setGeometry(QtCore.QRect(630, 830, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rec5Labelartist.setFont(font)
        self.Rec5Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Rec5Labelartist.setText("")
        self.Rec5Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Rec5Labelartist.setObjectName("Rec5Labelartist")
        self.Top4LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Top4LabelSong.setGeometry(QtCore.QRect(1020, 730, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top4LabelSong.setFont(font)
        self.Top4LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top4LabelSong.setText("")
        self.Top4LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Top4LabelSong.setObjectName("Top4LabelSong")
        self.Top2Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Top2Labelartist.setGeometry(QtCore.QRect(1410, 620, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top2Labelartist.setFont(font)
        self.Top2Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top2Labelartist.setText("")
        self.Top2Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Top2Labelartist.setObjectName("Top2Labelartist")
        self.Top3Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Top3Labelartist.setGeometry(QtCore.QRect(1410, 690, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top3Labelartist.setFont(font)
        self.Top3Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top3Labelartist.setText("")
        self.Top3Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Top3Labelartist.setObjectName("Top3Labelartist")
        self.Top4Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Top4Labelartist.setGeometry(QtCore.QRect(1410, 760, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top4Labelartist.setFont(font)
        self.Top4Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top4Labelartist.setText("")
        self.Top4Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Top4Labelartist.setObjectName("Top4Labelartist")
        self.Top1Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Top1Labelartist.setGeometry(QtCore.QRect(1410, 550, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top1Labelartist.setFont(font)
        self.Top1Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top1Labelartist.setText("")
        self.Top1Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Top1Labelartist.setObjectName("Top1Labelartist")
        self.Top5Labelartist = QtWidgets.QLabel(self.centralwidget)
        self.Top5Labelartist.setGeometry(QtCore.QRect(1410, 830, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top5Labelartist.setFont(font)
        self.Top5Labelartist.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top5Labelartist.setText("")
        self.Top5Labelartist.setAlignment(QtCore.Qt.AlignCenter)
        self.Top5Labelartist.setObjectName("Top5Labelartist")
        self.Top5LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Top5LabelSong.setGeometry(QtCore.QRect(1020, 800, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top5LabelSong.setFont(font)
        self.Top5LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top5LabelSong.setText("")
        self.Top5LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Top5LabelSong.setObjectName("Top5LabelSong")
        self.Top3LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Top3LabelSong.setGeometry(QtCore.QRect(1020, 660, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top3LabelSong.setFont(font)
        self.Top3LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top3LabelSong.setText("")
        self.Top3LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Top3LabelSong.setObjectName("Top3LabelSong")
        self.Top2LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Top2LabelSong.setGeometry(QtCore.QRect(1020, 590, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top2LabelSong.setFont(font)
        self.Top2LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top2LabelSong.setText("")
        self.Top2LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Top2LabelSong.setObjectName("Top2LabelSong")
        self.Top1LabelSong = QtWidgets.QLabel(self.centralwidget)
        self.Top1LabelSong.setGeometry(QtCore.QRect(1020, 520, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Top1LabelSong.setFont(font)
        self.Top1LabelSong.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Top1LabelSong.setText("")
        self.Top1LabelSong.setAlignment(QtCore.Qt.AlignCenter)
        self.Top1LabelSong.setObjectName("Top1LabelSong")
        RecPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RecPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        RecPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RecPage)
        self.statusbar.setObjectName("statusbar")
        RecPage.setStatusBar(self.statusbar)

        self.retranslateUi(RecPage)
        QtCore.QMetaObject.connectSlotsByName(RecPage)

    def retranslateUi(self, RecPage):
        _translate = QtCore.QCoreApplication.translate
        RecPage.setWindowTitle(_translate("RecPage", "MainWindow"))
        self.RecBackBtn.setText(_translate("RecPage", "<"))
        self.GenerateBtn.setText(_translate("RecPage", "Generate "))
        self.label_2.setText(_translate("RecPage", "My Top 5 Song of the day"))
        self.label_3.setText(_translate("RecPage", "Top 5 Songs  Spotify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecPage = QtWidgets.QMainWindow()
    ui = Ui_RecPage()
    ui.setupUi(RecPage)
    RecPage.show()
    sys.exit(app.exec_())
