# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\Second_Cyourse-main\Suckond_course_finals\WeekendPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeekendPage(object):
    def setupUi(self, WeekendPage):
        WeekendPage.setObjectName("WeekendPage")
        WeekendPage.resize(1920, 1080)
        WeekendPage.setMinimumSize(QtCore.QSize(1920, 1080))
        WeekendPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(WeekendPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\Second_Cyourse-main\\Suckond_course_finals\\weekendPage.png"))
        self.label.setObjectName("label")
        self.WeekendBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.WeekendBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.WeekendBackBtn.setFont(font)
        self.WeekendBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.WeekendBackBtn.setObjectName("WeekendBackBtn")
        self.DateWeekendComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateWeekendComboBox.setGeometry(QtCore.QRect(350, 560, 301, 41))
        self.DateWeekendComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateWeekendComboBox.setObjectName("DateWeekendComboBox")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.WeekendPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.WeekendPriceLabel.setGeometry(QtCore.QRect(70, 490, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.WeekendPriceLabel.setFont(font)
        self.WeekendPriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.WeekendPriceLabel.setObjectName("WeekendPriceLabel")
        self.DateWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateWeekendLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateWeekendLabel.setFont(font)
        self.DateWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateWeekendLabel.setObjectName("DateWeekendLabel")
        self.QuantityWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityWeekendLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityWeekendLabel.setFont(font)
        self.QuantityWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityWeekendLabel.setObjectName("QuantityWeekendLabel")
        self.ConfirmWeekendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmWeekendBtn.setGeometry(QtCore.QRect(460, 930, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmWeekendBtn.setFont(font)
        self.ConfirmWeekendBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmWeekendBtn.setObjectName("ConfirmWeekendBtn")
        self.RowWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowWeekendLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowWeekendLabel.setFont(font)
        self.RowWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowWeekendLabel.setObjectName("RowWeekendLabel")
        self.SeatWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatWeekendLabel.setGeometry(QtCore.QRect(70, 740, 581, 131))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatWeekendLabel.setFont(font)
        self.SeatWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatWeekendLabel.setObjectName("SeatWeekendLabel")
        self.RowWeekendComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowWeekendComboBox.setGeometry(QtCore.QRect(350, 680, 301, 41))
        self.RowWeekendComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowWeekendComboBox.setObjectName("RowWeekendComboBox")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.TotalWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalWeekendLabel.setGeometry(QtCore.QRect(150, 880, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalWeekendLabel.setFont(font)
        self.TotalWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalWeekendLabel.setObjectName("TotalWeekendLabel")
        self.TotalWeekendLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalWeekendLabelValue.setGeometry(QtCore.QRect(350, 880, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalWeekendLabelValue.setFont(font)
        self.TotalWeekendLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalWeekendLabelValue.setObjectName("TotalWeekendLabelValue")
        self.PayWeekendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayWeekendBtn.setEnabled(False)
        self.PayWeekendBtn.setGeometry(QtCore.QRect(600, 930, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayWeekendBtn.setFont(font)
        self.PayWeekendBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayWeekendBtn.setObjectName("PayWeekendBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 620, 301, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.WeekendBalanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.WeekendBalanceLabel.setGeometry(QtCore.QRect(350, 490, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.WeekendBalanceLabel.setFont(font)
        self.WeekendBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.WeekendBalanceLabel.setObjectName("WeekendBalanceLabel")
        self.QuantityCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QuantityCheckBtn.setGeometry(QtCore.QRect(660, 820, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityCheckBtn.setFont(font)
        self.QuantityCheckBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.QuantityCheckBtn.setObjectName("QuantityCheckBtn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(350, 740, 301, 130))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SeatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SeatLayout.setContentsMargins(0, 0, 0, 0)
        self.SeatLayout.setObjectName("SeatLayout")
        self.checkBox26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox26.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox26.setObjectName("checkBox26")
        self.SeatLayout.addWidget(self.checkBox26, 0, 5, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox29.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox29.setObjectName("checkBox29")
        self.SeatLayout.addWidget(self.checkBox29, 3, 5, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox19.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox19.setObjectName("checkBox19")
        self.SeatLayout.addWidget(self.checkBox19, 3, 3, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox9.setObjectName("checkBox9")
        self.SeatLayout.addWidget(self.checkBox9, 3, 1, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox24.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox24.setObjectName("checkBox24")
        self.SeatLayout.addWidget(self.checkBox24, 3, 4, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox6.setObjectName("checkBox6")
        self.SeatLayout.addWidget(self.checkBox6, 0, 1, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox22.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox22.setObjectName("checkBox22")
        self.SeatLayout.addWidget(self.checkBox22, 1, 4, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox28.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox28.setObjectName("checkBox28")
        self.SeatLayout.addWidget(self.checkBox28, 2, 5, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox17.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox17.setObjectName("checkBox17")
        self.SeatLayout.addWidget(self.checkBox17, 1, 3, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox21.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox21.setObjectName("checkBox21")
        self.SeatLayout.addWidget(self.checkBox21, 0, 4, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox13.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox13.setObjectName("checkBox13")
        self.SeatLayout.addWidget(self.checkBox13, 2, 2, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox30.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox30.setObjectName("checkBox30")
        self.SeatLayout.addWidget(self.checkBox30, 4, 5, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox11.setObjectName("checkBox11")
        self.SeatLayout.addWidget(self.checkBox11, 0, 2, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox15.setObjectName("checkBox15")
        self.SeatLayout.addWidget(self.checkBox15, 4, 2, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox16.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox16.setObjectName("checkBox16")
        self.SeatLayout.addWidget(self.checkBox16, 0, 3, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox23.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox23.setObjectName("checkBox23")
        self.SeatLayout.addWidget(self.checkBox23, 2, 4, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox1.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox1.setObjectName("checkBox1")
        self.SeatLayout.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox3.setObjectName("checkBox3")
        self.SeatLayout.addWidget(self.checkBox3, 2, 0, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox20.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox20.setObjectName("checkBox20")
        self.SeatLayout.addWidget(self.checkBox20, 4, 3, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox18.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox18.setObjectName("checkBox18")
        self.SeatLayout.addWidget(self.checkBox18, 2, 3, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox2.setObjectName("checkBox2")
        self.SeatLayout.addWidget(self.checkBox2, 1, 0, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox27.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox27.setObjectName("checkBox27")
        self.SeatLayout.addWidget(self.checkBox27, 1, 5, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox4.setObjectName("checkBox4")
        self.SeatLayout.addWidget(self.checkBox4, 3, 0, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox10.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox10.setObjectName("checkBox10")
        self.SeatLayout.addWidget(self.checkBox10, 4, 1, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox14.setObjectName("checkBox14")
        self.SeatLayout.addWidget(self.checkBox14, 3, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox12.setObjectName("checkBox12")
        self.SeatLayout.addWidget(self.checkBox12, 1, 2, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox5.setObjectName("checkBox5")
        self.SeatLayout.addWidget(self.checkBox5, 4, 0, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox7.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox7.setObjectName("checkBox7")
        self.SeatLayout.addWidget(self.checkBox7, 1, 1, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox8.setObjectName("checkBox8")
        self.SeatLayout.addWidget(self.checkBox8, 2, 1, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox25.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox25.setObjectName("checkBox25")
        self.SeatLayout.addWidget(self.checkBox25, 4, 4, 1, 1)
        self.checkBox26.raise_()
        self.checkBox4.raise_()
        self.checkBox14.raise_()
        self.checkBox3.raise_()
        self.checkBox21.raise_()
        self.checkBox17.raise_()
        self.checkBox11.raise_()
        self.checkBox10.raise_()
        self.checkBox9.raise_()
        self.checkBox2.raise_()
        self.checkBox27.raise_()
        self.checkBox29.raise_()
        self.checkBox19.raise_()
        self.checkBox24.raise_()
        self.checkBox6.raise_()
        self.checkBox13.raise_()
        self.checkBox30.raise_()
        self.checkBox22.raise_()
        self.checkBox28.raise_()
        self.checkBox18.raise_()
        self.checkBox15.raise_()
        self.checkBox8.raise_()
        self.checkBox1.raise_()
        self.checkBox16.raise_()
        self.checkBox23.raise_()
        self.checkBox20.raise_()
        self.checkBox12.raise_()
        self.checkBox5.raise_()
        self.checkBox7.raise_()
        self.checkBox25.raise_()
        self.BalanceNotEnoughMessage = QtWidgets.QLabel(self.centralwidget)
        self.BalanceNotEnoughMessage.setEnabled(False)
        self.BalanceNotEnoughMessage.setGeometry(QtCore.QRect(660, 490, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BalanceNotEnoughMessage.setFont(font)
        self.BalanceNotEnoughMessage.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BalanceNotEnoughMessage.setText("")
        self.BalanceNotEnoughMessage.setObjectName("BalanceNotEnoughMessage")
        WeekendPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeekendPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        WeekendPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeekendPage)
        self.statusbar.setObjectName("statusbar")
        WeekendPage.setStatusBar(self.statusbar)

        self.retranslateUi(WeekendPage)
        QtCore.QMetaObject.connectSlotsByName(WeekendPage)

    def retranslateUi(self, WeekendPage):
        _translate = QtCore.QCoreApplication.translate
        WeekendPage.setWindowTitle(_translate("WeekendPage", "MainWindow"))
        self.WeekendBackBtn.setText(_translate("WeekendPage", "<"))
        self.DateWeekendComboBox.setItemText(0, _translate("WeekendPage", "5 July – Las Vegas, NV @ Allegiant Stadium "))
        self.DateWeekendComboBox.setItemText(1, _translate("WeekendPage", "8 July -  Santa Clara, CA @ Levi’s Stadium"))
        self.DateWeekendComboBox.setItemText(2, _translate("WeekendPage", "9 July -Santa Clara, CA @ Levi’s Stadium"))
        self.DateWeekendComboBox.setItemText(3, _translate("WeekendPage", "12 July -Seattle, WA @ Lumen Field "))
        self.DateWeekendComboBox.setItemText(4, _translate("WeekendPage", "15 July -Vancouver, BC @ BC Place"))
        self.DateWeekendComboBox.setItemText(5, _translate("WeekendPage", "16 July - Vancouver, BC @ BC Place"))
        self.DateWeekendComboBox.setItemText(6, _translate("WeekendPage", "19 July -  Edmonton, AB @ Commonwealth Stadium"))
        self.DateWeekendComboBox.setItemText(7, _translate("WeekendPage", "24 July -Montreal, QC @ Parc Jean‑Drapeau"))
        self.DateWeekendComboBox.setItemText(8, _translate("WeekendPage", "25 July -Montreal, QC @ Parc Jean‑Drapeau"))
        self.DateWeekendComboBox.setItemText(9, _translate("WeekendPage", "27 July - Toronto, ON @ Rogers Centre"))
        self.DateWeekendComboBox.setItemText(10, _translate("WeekendPage", "28 July - Toronto, ON @ Rogers Centre"))
        self.DateWeekendComboBox.setItemText(11, _translate("WeekendPage", "30 July -Philadelphia, PA @ Lincoln Financial Field"))
        self.DateWeekendComboBox.setItemText(12, _translate("WeekendPage", "31 July -Philadelphia, PA @ Lincoln Financial Field"))
        self.DateWeekendComboBox.setItemText(13, _translate("WeekendPage", "2 August - Landover, MD @ Northwest Stadium"))
        self.DateWeekendComboBox.setItemText(14, _translate("WeekendPage", "12 August -Nashville, TN @ Nissan Stadium"))
        self.DateWeekendComboBox.setItemText(15, _translate("WeekendPage", "15 August -Miami Gardens, FL @ Hard Rock Stadium "))
        self.DateWeekendComboBox.setItemText(16, _translate("WeekendPage", "21 August -Atlanta, GA @ Mercedes‑Benz Stadium"))
        self.DateWeekendComboBox.setItemText(17, _translate("WeekendPage", "24 August -Orlando, FL @ Camping World Stadium"))
        self.DateWeekendComboBox.setItemText(18, _translate("WeekendPage", "27 August -Arlington, TX @ AT&T Stadium"))
        self.DateWeekendComboBox.setItemText(19, _translate("WeekendPage", "28 August -Arlington, TX @ AT&T Stadium"))
        self.DateWeekendComboBox.setItemText(20, _translate("WeekendPage", "30 August - Houston, TX @ NRG Stadium"))
        self.DateWeekendComboBox.setItemText(21, _translate("WeekendPage", "31 August - Houston, TX @ NRG Stadium"))
        self.DateWeekendComboBox.setItemText(22, _translate("WeekendPage", "3 September -  San Antonio, TX @ Alamodome"))
        self.WeekendPriceLabel.setText(_translate("WeekendPage", "Price : 450$"))
        self.DateWeekendLabel.setText(_translate("WeekendPage", "Date & City"))
        self.QuantityWeekendLabel.setText(_translate("WeekendPage", "Quantity"))
        self.ConfirmWeekendBtn.setText(_translate("WeekendPage", "Confirm "))
        self.RowWeekendLabel.setText(_translate("WeekendPage", "The Row"))
        self.SeatWeekendLabel.setText(_translate("WeekendPage", "The seat"))
        self.RowWeekendComboBox.setItemText(0, _translate("WeekendPage", "1"))
        self.RowWeekendComboBox.setItemText(1, _translate("WeekendPage", "2"))
        self.RowWeekendComboBox.setItemText(2, _translate("WeekendPage", "3"))
        self.RowWeekendComboBox.setItemText(3, _translate("WeekendPage", "4"))
        self.RowWeekendComboBox.setItemText(4, _translate("WeekendPage", "5"))
        self.RowWeekendComboBox.setItemText(5, _translate("WeekendPage", "6"))
        self.RowWeekendComboBox.setItemText(6, _translate("WeekendPage", "7"))
        self.RowWeekendComboBox.setItemText(7, _translate("WeekendPage", "8"))
        self.RowWeekendComboBox.setItemText(8, _translate("WeekendPage", "9"))
        self.RowWeekendComboBox.setItemText(9, _translate("WeekendPage", "10"))
        self.RowWeekendComboBox.setItemText(10, _translate("WeekendPage", "11"))
        self.RowWeekendComboBox.setItemText(11, _translate("WeekendPage", "12"))
        self.RowWeekendComboBox.setItemText(12, _translate("WeekendPage", "13"))
        self.RowWeekendComboBox.setItemText(13, _translate("WeekendPage", "14"))
        self.RowWeekendComboBox.setItemText(14, _translate("WeekendPage", "15"))
        self.RowWeekendComboBox.setItemText(15, _translate("WeekendPage", "16"))
        self.RowWeekendComboBox.setItemText(16, _translate("WeekendPage", "17"))
        self.RowWeekendComboBox.setItemText(17, _translate("WeekendPage", "18"))
        self.RowWeekendComboBox.setItemText(18, _translate("WeekendPage", "19"))
        self.RowWeekendComboBox.setItemText(19, _translate("WeekendPage", "20"))
        self.RowWeekendComboBox.setItemText(20, _translate("WeekendPage", "21"))
        self.RowWeekendComboBox.setItemText(21, _translate("WeekendPage", "22"))
        self.RowWeekendComboBox.setItemText(22, _translate("WeekendPage", "23"))
        self.RowWeekendComboBox.setItemText(23, _translate("WeekendPage", "24"))
        self.RowWeekendComboBox.setItemText(24, _translate("WeekendPage", "25"))
        self.RowWeekendComboBox.setItemText(25, _translate("WeekendPage", "26"))
        self.RowWeekendComboBox.setItemText(26, _translate("WeekendPage", "27"))
        self.RowWeekendComboBox.setItemText(27, _translate("WeekendPage", "28"))
        self.RowWeekendComboBox.setItemText(28, _translate("WeekendPage", "29"))
        self.RowWeekendComboBox.setItemText(29, _translate("WeekendPage", "30"))
        self.TotalWeekendLabel.setText(_translate("WeekendPage", "In Total"))
        self.TotalWeekendLabelValue.setText(_translate("WeekendPage", "0$"))
        self.PayWeekendBtn.setText(_translate("WeekendPage", "Choose The Quantity First"))
        self.WeekendBalanceLabel.setText(_translate("WeekendPage", "Balance:"))
        self.QuantityCheckBtn.setText(_translate("WeekendPage", "✓"))
        self.checkBox26.setText(_translate("WeekendPage", "26"))
        self.checkBox29.setText(_translate("WeekendPage", "29"))
        self.checkBox19.setText(_translate("WeekendPage", "19"))
        self.checkBox9.setText(_translate("WeekendPage", "9"))
        self.checkBox24.setText(_translate("WeekendPage", "24"))
        self.checkBox6.setText(_translate("WeekendPage", "6"))
        self.checkBox22.setText(_translate("WeekendPage", "22"))
        self.checkBox28.setText(_translate("WeekendPage", "28"))
        self.checkBox17.setText(_translate("WeekendPage", "17"))
        self.checkBox21.setText(_translate("WeekendPage", "21"))
        self.checkBox13.setText(_translate("WeekendPage", "13"))
        self.checkBox30.setText(_translate("WeekendPage", "30"))
        self.checkBox11.setText(_translate("WeekendPage", "11"))
        self.checkBox15.setText(_translate("WeekendPage", "15"))
        self.checkBox16.setText(_translate("WeekendPage", "16"))
        self.checkBox23.setText(_translate("WeekendPage", "23"))
        self.checkBox1.setText(_translate("WeekendPage", "1"))
        self.checkBox3.setText(_translate("WeekendPage", "3"))
        self.checkBox20.setText(_translate("WeekendPage", "20"))
        self.checkBox18.setText(_translate("WeekendPage", "18"))
        self.checkBox2.setText(_translate("WeekendPage", "2"))
        self.checkBox27.setText(_translate("WeekendPage", "27"))
        self.checkBox4.setText(_translate("WeekendPage", "4"))
        self.checkBox10.setText(_translate("WeekendPage", "10"))
        self.checkBox14.setText(_translate("WeekendPage", "14"))
        self.checkBox12.setText(_translate("WeekendPage", "12"))
        self.checkBox5.setText(_translate("WeekendPage", "5"))
        self.checkBox7.setText(_translate("WeekendPage", "7"))
        self.checkBox8.setText(_translate("WeekendPage", "8"))
        self.checkBox25.setText(_translate("WeekendPage", "25"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeekendPage = QtWidgets.QMainWindow()
    ui = Ui_WeekendPage()
    ui.setupUi(WeekendPage)
    WeekendPage.show()
    sys.exit(app.exec_())
